MysqlInit:
  Host: "14.103.171.130"
  Port: 3306
  User: "root"
  Password: "4ay1nkal3u8ed77y"
  Database: "coupontemporarily"

RedisInit:
  Host: "14.103.171.130"
  Port: 6379
  Password: "4ay1nkal3u8ed77y"
  Database: 4

AesConfig:
  AesKey: "1234567890123456" # AES加密密钥（16、24或32字节）
